# Generated by Django 5.1 on 2024-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_pubdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msgId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(default='', max_length=50)),
                ('userEmail', models.CharField(default='', max_length=50)),
                ('userPhone', models.CharField(default='', max_length=15)),
                ('userMessage', models.CharField(default='', max_length=500)),
                ('messageDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
