# Generated by Django 5.1 on 2024-09-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('updateId', models.AutoField(primary_key=True, serialize=False)),
                ('ordId', models.IntegerField()),
                ('updates', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
